version: '3'
services:
  wa_backend:
    build:
      context: .
    ports: 
      - "5000:5000"
    environment: 
      - FLASK_APP=wa_backend
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - JSON_FILE_PATH=todolist.json
      - DATABASE_URL=sqlite:///database.db
    
